import "server-only";
import type { NeonQueryFunction } from "@neondatabase/serverless";
import { calculateAgentDna, DNA_VERSION } from "@/lib/analytics/agent-dna";
import { calculateArenaScores, ARENA_SCORE_VERSION, type ScoreInput } from "@/lib/analytics/arena-score";
type Sql=NeonQueryFunction<false,false>;
type MetricRow={agent_id:string;portfolio_value_usd:string;realized_pnl_usd:string;unrealized_pnl_usd:string;roi:string;win_rate:string;max_drawdown:string;trade_count:string;volume_usd:string;created_at:string;first_trade:string|null;battle_win_rate:string};
type TradeRow={id:string;agent_id:string;side:"buy"|"sell";symbol:string;asset_address:string;quantity:string;price_usd:string;quote_amount_usd:string|null;realized_pnl_usd:string|null;traded_at:string;tx_hash:string};
const n=(v:string|null|undefined)=>Number(v??0);
function consistency(values:number[]){if(values.length<2)return 0;let positive=0;for(let i=1;i<values.length;i++)if(values[i]>=values[i-1])positive++;return positive/(values.length-1)*100}
function behaviorStats(trades:TradeRow[],portfolio:number,positions:Array<{market_value_usd:string}>){
  const sorted=[...trades].sort((a,b)=>new Date(a.traded_at).getTime()-new Date(b.traded_at).getTime()),first=sorted[0],last=sorted.at(-1);const days=first&&last?Math.max(1,(new Date(last.traded_at).getTime()-new Date(first.traded_at).getTime())/86_400_000):1;
  const queues=new Map<string,Array<{quantity:number;time:number}>>(),holds:number[]=[];let momentum=0,comparisons=0;const priorPrice=new Map<string,number>();
  for(const trade of sorted){const asset=trade.asset_address,qty=n(trade.quantity),time=new Date(trade.traded_at).getTime(),price=n(trade.price_usd),q=queues.get(asset)??[];const previous=priorPrice.get(asset);if(previous&&previous!==price){comparisons++;if((trade.side==="buy"&&price>previous)||(trade.side==="sell"&&price<previous))momentum++}priorPrice.set(asset,price);if(trade.side==="buy")q.push({quantity:qty,time});else{let remaining=qty;while(remaining>0&&q.length){const lot=q[0],used=Math.min(remaining,lot.quantity);holds.push((time-lot.time)/60_000);lot.quantity-=used;remaining-=used;if(lot.quantity<=1e-12)q.shift()}}queues.set(asset,q)}
  const values=positions.map(x=>n(x.market_value_usd)),total=values.reduce((a,b)=>a+b,0),largest=total?Math.max(0,...values)/total:0,assets=new Set(trades.map(x=>x.asset_address)).size,avgTrade=trades.length?trades.reduce((s,x)=>s+n(x.quote_amount_usd),0)/trades.length:0,wins=trades.filter(x=>n(x.realized_pnl_usd)>0).length,closed=trades.filter(x=>x.side==="sell").length;
  return{observedDays:days,averageHoldMinutes:holds.length?holds.reduce((a,b)=>a+b,0)/holds.length:null,tradeFrequency:trades.length/days,turnover:portfolio?trades.reduce((s,x)=>s+n(x.quote_amount_usd),0)/portfolio:0,averageTradeUsd:avgTrade,largestPositionShare:largest,assetCount:assets,profitableTradeShare:closed?wins/closed:0,momentumTradeShare:comparisons?momentum/comparisons:0};
}
export async function recalculatePlatformAnalytics(sql:Sql){
  const results=await Promise.all([
    sql.query("select m.*,a.created_at,min(t.traded_at) as first_trade,coalesce((select count(*) filter(where br.winner_agent_id=m.agent_id)::numeric/nullif(count(*),0)*100 from battle_results br join battle_participants bp on bp.battle_id=br.battle_id where bp.agent_id=m.agent_id),0) battle_win_rate from agent_metrics m join agents a on a.id=m.agent_id left join normalized_trades t on t.agent_id=m.agent_id where a.verified_at is not null or a.identity_type='observed_wallet' group by m.agent_id,a.created_at"),
    sql.query("select t.id,t.agent_id,t.side,t.symbol,t.asset_address,t.quantity,t.price_usd,t.quote_amount_usd,t.realized_pnl_usd,t.traded_at,x.tx_hash from normalized_trades t join transactions x on x.id=t.transaction_id order by t.traded_at"),
    sql.query("select agent_id,market_value_usd from positions where quantity>0"),
    sql.query("select agent_id,equity_usd from portfolio_snapshots where captured_at>now()-interval '30 days' order by captured_at"),
  ]);
  const metricRows=results[0] as MetricRow[],tradeRows=results[1] as TradeRow[],positionRows=results[2] as Array<{agent_id:string;market_value_usd:string}>,snapshotRows=results[3] as Array<{agent_id:string;equity_usd:string}>;
  const grouped=<T extends{agent_id:string}>(rows:T[])=>{const m=new Map<string,T[]>();for(const row of rows)m.set(row.agent_id,[...(m.get(row.agent_id)??[]),row]);return m},tradesBy=grouped(tradeRows),positionsBy=grouped(positionRows),snapshotsBy=grouped(snapshotRows);
  const scoreInputs:ScoreInput[]=[];
  const behaviorQueries=[];
  for(const row of metricRows){const trades=tradesBy.get(row.agent_id)??[],stats=behaviorStats(trades,n(row.portfolio_value_usd),positionsBy.get(row.agent_id)??[]),dna=calculateAgentDna({tradeCount:n(row.trade_count),observedDays:stats.observedDays,averageHoldMinutes:stats.averageHoldMinutes,turnover:stats.turnover,averageTradeUsd:stats.averageTradeUsd,portfolioValueUsd:n(row.portfolio_value_usd),largestPositionShare:stats.largestPositionShare,assetCount:stats.assetCount,winRate:n(row.win_rate),maxDrawdown:n(row.max_drawdown),profitableTradeShare:stats.profitableTradeShare,momentumTradeShare:stats.momentumTradeShare});const favorite=[...new Set(trades.map(x=>x.symbol))].sort((a,b)=>trades.filter(x=>x.symbol===b).length-trades.filter(x=>x.symbol===a).length)[0]??null;const profitable=[...new Set(trades.map(x=>x.symbol))].sort((a,b)=>trades.filter(x=>x.symbol===b).reduce((s,x)=>s+n(x.realized_pnl_usd),0)-trades.filter(x=>x.symbol===a).reduce((s,x)=>s+n(x.realized_pnl_usd),0))[0]??null;
    behaviorQueries.push(sql`insert into agent_behavior_profiles(agent_id,aggression,patience,diversification,consistency,momentum_bias,risk_control,activity,primary_archetype,secondary_archetype,typical_hold_minutes,trade_frequency_daily,average_trade_usd,turnover,concentration,favorite_asset,most_profitable_asset,most_traded_asset,risk_level,sample_size,calculation_version,calculated_at) values(${row.agent_id},${dna.aggression},${dna.patience},${dna.diversification},${dna.consistency},${dna.momentumBias},${dna.riskControl},${dna.activity},${dna.primaryArchetype},${dna.secondaryArchetype},${stats.averageHoldMinutes},${stats.tradeFrequency},${stats.averageTradeUsd},${stats.turnover},${stats.largestPositionShare},${favorite},${profitable},${favorite},${dna.riskLevel},${trades.length},${DNA_VERSION},now()) on conflict(agent_id) do update set aggression=excluded.aggression,patience=excluded.patience,diversification=excluded.diversification,consistency=excluded.consistency,momentum_bias=excluded.momentum_bias,risk_control=excluded.risk_control,activity=excluded.activity,primary_archetype=excluded.primary_archetype,secondary_archetype=excluded.secondary_archetype,typical_hold_minutes=excluded.typical_hold_minutes,trade_frequency_daily=excluded.trade_frequency_daily,average_trade_usd=excluded.average_trade_usd,turnover=excluded.turnover,concentration=excluded.concentration,favorite_asset=excluded.favorite_asset,most_profitable_asset=excluded.most_profitable_asset,most_traded_asset=excluded.most_traded_asset,risk_level=excluded.risk_level,sample_size=excluded.sample_size,calculation_version=excluded.calculation_version,calculated_at=now()`);
    scoreInputs.push({id:row.agent_id,roi:n(row.roi)/(1+Math.abs(n(row.max_drawdown))),realizedPnl:n(row.realized_pnl_usd),winRate:n(row.win_rate),maxDrawdown:n(row.max_drawdown),consistency:consistency((snapshotsBy.get(row.agent_id)??[]).map(x=>n(x.equity_usd))),tradeCount:n(row.trade_count),observedDays:stats.observedDays,battleWinRate:n(row.battle_win_rate)});
  }
  if(behaviorQueries.length)await sql.transaction(behaviorQueries);
  const scores=calculateArenaScores(scoreInputs),scoreQueries=scores.map((result,index)=>sql`insert into agent_score_snapshots(agent_id,arena_score,return_score,pnl_score,risk_score,win_rate_score,consistency_score,activity_score,longevity_score,battle_score,rank,sample_size,eligible,calculation_version) values(${result.agentId},${result.arenaScore},${result.components.return},${result.components.pnl},${result.components.risk},${result.components.winRate},${result.components.consistency},${result.components.activity},${result.components.longevity},${result.components.battle},${index+1},${result.sampleSize},${result.eligible},${ARENA_SCORE_VERSION})`);if(scoreQueries.length)await sql.transaction(scoreQueries);
  const eventQueries=tradeRows.map(trade=>sql`insert into agent_events(agent_id,event_type,event_timestamp,transaction_hash,token_address,metadata,severity,dedupe_key) values(${trade.agent_id},${trade.side==="buy"?"agent_trade_buy":"agent_trade_sell"},${trade.traded_at},${trade.tx_hash},${trade.asset_address},${JSON.stringify({symbol:trade.symbol,side:trade.side,valueUsd:n(trade.quote_amount_usd),realizedPnlUsd:n(trade.realized_pnl_usd)})}::jsonb,${n(trade.realized_pnl_usd)<-1000?"critical":n(trade.realized_pnl_usd)>1000?"positive":"info"},${`trade:${trade.id}`}) on conflict(dedupe_key) do nothing`);if(eventQueries.length)await sql.transaction(eventQueries);
  return{agents:metricRows.length,scores:scores.length,events:eventQueries.length};
}
