import { test,expect } from "@playwright/test";
test("live arena and upstream health work",async({page,request})=>{await page.goto("/");await expect(page.getByRole("heading",{name:/AI agents are trading/})).toBeVisible();await page.getByRole("tab",{name:"24H P&L"}).click();const health=await request.get("/api/health");expect(health.ok()).toBeTruthy();expect((await health.json()).mode).toBe("live")});
test("live Stock Token market and search work",async({page,request})=>{await page.goto("/stock-tokens");await expect(page.getByRole("heading",{name:/STOCK TOKEN/})).toBeVisible();const stock=await request.get("/api/stock-tokens/AAPL");expect(stock.ok()).toBeTruthy();expect((await stock.json()).data.symbol).toBe("AAPL");const search=await request.get("/api/search?q=AAPL");expect((await search.json()).data.length).toBeGreaterThan(0)});
test("registration and protected dashboard render",async({page})=>{await page.goto("/register");await expect(page.getByRole("heading",{name:/REGISTER/})).toBeVisible();await page.goto("/dashboard");await expect(page.getByText("Authentication required")).toBeVisible()});
test("API discovery and address lookup work without registration",async({page,request,isMobile})=>{test.setTimeout(120_000);test.skip(isMobile);const address="0x2ccc152ad68419f777531e6a40a52325e2a80ee2";const discovery=await request.get("/api/discover");expect(discovery.ok()).toBeTruthy();expect((await discovery.json()).data.length).toBeGreaterThan(0);await page.goto("/discover");await page.getByLabel("Wallet address").fill(address);await page.getByRole("button",{name:/ADD & ANALYZE/}).click();await expect(page.getByRole("heading",{name:/WALLET/})).toBeVisible({timeout:90_000});await expect(page.getByText("LIVE HOLDINGS")).toBeVisible({timeout:30_000})});
test("mobile navigation opens",async({page,isMobile})=>{test.skip(!isMobile);await page.goto("/");await page.getByRole("button",{name:"Toggle menu"}).click();await expect(page.getByRole("link",{name:"Markets"})).toBeVisible()});
test("V2 live, markets, compare, hall, and API envelopes work",async({page,request})=>{await page.goto("/live");await expect(page.getByRole("heading",{name:"LIVE ARENA"})).toBeVisible();await page.goto("/markets/AAPL");await expect(page.getByRole("heading",{name:"AAPL"})).toBeVisible();await page.goto("/compare");await expect(page.getByRole("heading",{name:"AGENT COMPARE"})).toBeVisible();await page.goto("/hall");await expect(page.getByRole("heading",{name:"THE HALL"})).toBeVisible();for(const route of["/api/v1/events","/api/v1/tokens/AAPL","/api/v1/market/consensus","/api/v1/battles"]){const response=await request.get(route);expect(response.ok()).toBeTruthy();const body=await response.json();expect(body.error).toBeNull();expect(body.meta.requestId).toBeTruthy()}});

test("observed competitors populate the registry and battle selector",async({page,request})=>{test.setTimeout(90_000);const agents=await request.get("/api/v1/agents");expect(agents.ok()).toBeTruthy();const agentBody=await agents.json();expect(agentBody.meta.observed).toBeGreaterThan(0);const discovery=await request.get("/api/v1/agents/discover");expect(discovery.ok()).toBeTruthy();expect((await discovery.json()).data.length).toBeGreaterThan(1);await page.goto("/agents");await expect(page.getByText("OBSERVED").first()).toBeVisible();await page.goto("/battles");await expect(page.getByRole("heading",{name:"START A LIVE BATTLE"})).toBeVisible();await expect(page.getByLabel("Competitor A")).toBeVisible();await expect(page.getByLabel("Competitor B")).toBeVisible()});
