import { z } from "zod";

const deploymentSchema=z.object({contractAddress:z.string().regex(/^0x[\da-fA-F]{40}$/),chainId:z.number(),networkName:z.string()});
const assetSchema=z.object({tokenSymbol:z.string(),tokenName:z.string(),deployments:z.array(deploymentSchema),currentMultiplier:z.string(),status:z.string(),logoUrl:z.string().url().optional(),tokenDecimals:z.number()});
const quoteSchema=z.object({tokenSymbol:z.string(),deployments:z.array(deploymentSchema),bid:z.string(),ask:z.string(),currency:z.literal("USD"),dailyTradingVolume:z.string(),isTradingHalt:z.boolean(),generatedAt:z.string(),dailyHigh:z.string().optional(),dailyLow:z.string().optional()});
const assetsResponse=z.object({assets:z.array(assetSchema)});const quoteResponse=z.object({quotes:z.array(quoteSchema)});
export type LiveStockToken={symbol:string;name:string;contractAddress:string;price:number;reference:number;bid:number;ask:number;day:number;volume:number;series:number[];updatedAt:string;halted:boolean;source:"Robinhood RHJ API";priceKind:"reference"};
const base="https://api.robinhood.com/rhj";
async function request(path:string){const response=await fetch(`${base}${path}`,{headers:{accept:"application/json"},next:{revalidate:15},signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new Error(`Robinhood Stock Token API unavailable (${response.status})`);return response.json()}
export async function getLiveStockTokens(symbols=["AAPL","NVDA","TSLA","MSFT"]):Promise<LiveStockToken[]>{const assets=assetsResponse.parse(await request("/assets")).assets;const quotes=await Promise.all(symbols.map(async symbol=>quoteResponse.parse(await request(`/prices/${symbol}`)).quotes[0]));return quotes.map(quote=>{if(!quote)throw new Error("Robinhood quote missing");const asset=assets.find(item=>item.tokenSymbol===quote.tokenSymbol),deployment=asset?.deployments.find(item=>item.chainId===4663)??quote.deployments.find(item=>item.chainId===4663);if(!asset||!deployment)throw new Error(`Canonical deployment missing for ${quote.tokenSymbol}`);const bid=Number(quote.bid),ask=Number(quote.ask),mid=(bid+ask)/2,multiplier=Number(asset.currentMultiplier),reference=mid*multiplier;return{symbol:quote.tokenSymbol,name:asset.tokenName,contractAddress:deployment.contractAddress,price:reference,reference,bid,ask,day:0,volume:Number(quote.dailyTradingVolume),series:[reference],updatedAt:quote.generatedAt,halted:quote.isTradingHalt,source:"Robinhood RHJ API",priceKind:"reference"}})}
