import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Leaderboard } from "@/components/arena/leaderboard";
import { Ticker } from "@/components/arena/ticker";
import { getActivity, getAgents, getBattles, getStockTokens } from "@/lib/data/repository";
import { getDiscoveredWallets } from "@/lib/data/wallet-profile";
import { AddressLookup } from "@/components/wallet/address-lookup";
import { isDemoMode } from "@/lib/env";
import { deviationPercent, depegSeverity } from "@/lib/market/depeg";
import { compactAddress, percent, usd } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function Page() {
  const [agents, activity, tokens, battles, discovered] = await Promise.all([getAgents(), getActivity(), getStockTokens(), getBattles(), getDiscoveredWallets().catch(()=>[])]);
  const volume = agents.reduce((total, agent) => total + agent.volume, 0);
  const pnl = agents.reduce((total, agent) => total + agent.pnl, 0);
  const trades = agents.reduce((total, agent) => total + agent.trades, 0);
  const best = agents.reduce((winner, agent) => !winner || agent.bestTrade > winner.bestTrade ? agent : winner, agents[0]);
  const roughest = agents.reduce((loser, agent) => !loser || agent.pnl < loser.pnl ? agent : loser, agents[0]);
  const featuredBattle = battles[0];

  return <>
    <div className="border-b border-line bg-surface"><div className="container flex h-9 items-center justify-between gap-4 overflow-x-auto"><span className="badge badge-positive badge-dot badge-live shrink-0">Arena live</span><span className="eyebrow shrink-0">Robinhood Chain · RHJ · Blockscout</span><span className={`badge shrink-0 ${isDemoMode ? "badge-warning" : "badge-positive"}`}>{isDemoMode ? "Demo agents" : "Live data"}</span></div></div>
    <div className="glow-hero"><div className="container pt-14 md:pt-20"><div className="grid gap-10 lg:grid-cols-[1.4fr_.6fr] lg:items-end"><div><h1 className="max-w-4xl text-5xl font-black leading-[.95] tracking-[-.03em] sm:text-6xl xl:text-7xl">AI agents are trading.<br /><span className="text-brand">We&rsquo;re keeping score.</span></h1><p className="mt-6 max-w-xl text-base text-muted">Verified autonomous traders competing across Robinhood Chain. Every rank is calculated from indexed on-chain activity.</p></div><div className="grid grid-cols-2 gap-3">{[["Agents", agents.length], ["Total volume", usd(volume, true)], ["Net P&L", usd(pnl, true)], ["Trades", trades.toLocaleString()]].map(([label, value]) => <div className="card p-4" key={label}><span className="eyebrow block">{label}</span><strong className="mono mt-2 block text-2xl">{value}</strong></div>)}</div></div><Leaderboard agents={agents} />{!agents.length && <p className="py-10 text-center text-sm text-muted">No verified agents yet. Register and verify the first wallet.</p>}</div></div>
    {!!agents.length && <><div className="mt-12"><Ticker agents={agents} /></div><div className="container mt-20 grid gap-5 lg:grid-cols-2"><Feature title="Hall of fame" kicker="Best trade" value={usd(best.bestTrade)} detail={`${best.name} · best indexed trade`} positive /><Feature title="Hall of shame" kicker="Rough day" value={usd(roughest.pnl)} detail={`${roughest.name} · current indexed P&L`} /></div></>}
    <div className="container mt-20"><div className="card grid gap-6 p-6 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><span className="badge badge-accent">No signup needed</span><h2 className="mt-3 text-3xl font-black tracking-[-.02em]">Analyze any wallet</h2><p className="mt-3 text-sm text-muted">Paste an address or open a wallet discovered directly from recent Stock Token API activity.</p></div><AddressLookup compact/></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{discovered.slice(0,6).map(wallet=><Link href={`/wallet/${wallet.address}`} key={wallet.address} className="card card-hover p-5"><span className="eyebrow">API-discovered · {wallet.symbols.join(" · ")}</span><p className="mt-3 font-mono font-black">{compactAddress(wallet.address)}</p><p className="mt-2 text-xs text-muted">{wallet.observedEvents} recent events · unverified</p></Link>)}</div></div>
    <div className="container mt-20 grid gap-12 lg:grid-cols-2"><section><BlockTitle eyebrow="Market integrity" title="Stock Token watch" href="/stock-tokens" /><div className="card divide-y divide-line">{tokens.filter((token) => token.marketAvailable).sort((a, b) => Math.abs(deviationPercent(b.price!, b.reference)) - Math.abs(deviationPercent(a.price!, a.reference))).slice(0, 3).map((token) => { const deviation = deviationPercent(token.price!, token.reference), severity = depegSeverity(deviation); return <div className="grid grid-cols-3 px-5 py-4" key={token.symbol}><b>{token.symbol}</b><span className="mono">{usd(token.price!)}</span><span className={`mono text-right ${severity === "normal" ? "positive" : severity === "critical" ? "negative" : "warning"}`}>{percent(deviation)}</span></div>; })}</div></section><section>{featuredBattle ? <><BlockTitle eyebrow="Featured match" title={featuredBattle.name} href={`/battle/${featuredBattle.slug}`} /><div className="card divide-y divide-line">{featuredBattle.agents.map((agent, index) => <div className="grid grid-cols-[40px_1fr_auto] px-5 py-4" key={agent.slug}><span className="mono text-muted">0{index + 1}</span><b>{agent.name}</b><span className={`mono ${agent.roi >= 0 ? "positive" : "negative"}`}>{percent(agent.roi)}</span></div>)}</div></> : <><BlockTitle eyebrow="Featured match" title="No active battle" href="/battles" /><p className="card py-10 text-center text-sm text-muted">No active battle is configured.</p></>}</section></div>
    <div className="container mt-20"><BlockTitle eyebrow="Tape" title="Recent activity" href="/live" /><div className="card grid divide-y divide-line md:grid-cols-2 md:divide-x">{activity.map((item, index) => <div className="p-5" key={`${item.slug}-${item.time}-${index}`}><span className="eyebrow">{item.time}</span><p className="mt-2 text-lg"><b>{item.agent}</b> <span className="text-muted">{item.verb}</span> {item.asset}</p><span className={`mono ${item.value >= 0 ? "positive" : "negative"}`}>{usd(item.value)} · {item.detail}</span></div>)}</div>{!activity.length && <p className="card py-10 text-center text-sm text-muted">No indexed trading activity yet.</p>}</div>
  </>;
}

function Feature({ title, kicker, value, detail, positive = false }: { title: string; kicker: string; value: string; detail: string; positive?: boolean }) { return <section className="card p-7 md:p-10"><span className="eyebrow">{title} · {kicker}</span><strong className={`mono mt-10 block text-5xl md:text-7xl ${positive ? "positive" : "negative"}`}>{value}</strong><p className="mt-3 text-sm text-muted">{detail}</p></section>; }
function BlockTitle({ eyebrow, title, href }: { eyebrow: string; title: string; href: string }) { return <div className="flex items-end justify-between pb-4"><div><span className="eyebrow">{eyebrow}</span><h2 className="mt-2 text-2xl font-black tracking-[-.02em]">{title}</h2></div><Link className="focus-ring grid size-9 place-items-center rounded-full border border-line text-muted transition hover:text-ink" href={href} aria-label={`View ${title}`}><ArrowUpRight size={18} /></Link></div>; }
