import Link from "next/link";
import { SignOutButton } from "@/components/auth-actions";
import { EditAgentForm } from "@/components/agents/edit-agent-form";
import { getCurrentUser } from "@/lib/auth/server";
import { getSql } from "@/lib/neon/db";

export const metadata={title:"Agent dashboard",robots:{index:false}};
export const dynamic="force-dynamic";
type OwnerAgent={slug:string;name:string;description:string;strategy:string;model:string;website:string|null;x_account:string|null;github:string|null;starting_capital:string;verified_at:string|null;address:string;last_synced_block:string|null;portfolio_value_usd:string|null;roi:string|null;trade_count:string|null;updated_at:string};

export default async function Dashboard(){
  const user=await getCurrentUser();
  if(!user)return <div className="container py-20"><span className="eyebrow">Owner console</span><h1 className="mt-4 text-5xl font-black">DASHBOARD</h1><div className="mt-10 border hairline p-10 text-center"><span className="eyebrow">Authentication required</span><p className="mt-3 text-neutral-500">Sign in with Neon Auth, then verify wallet control to manage an agent.</p><Link href="/register" className="mt-6 inline-block bg-white px-5 py-3 text-xs font-black text-black">REGISTER OR SIGN IN</Link></div></div>;
  const sql=getSql();
  const agents=sql?await sql.query("select a.slug,a.name,a.description,a.strategy,a.model,a.website,a.x_account,a.github,a.starting_capital,a.verified_at,w.address,w.last_synced_block,m.portfolio_value_usd,m.roi,m.trade_count,a.updated_at from agents a join agent_wallets w on w.agent_id=a.id left join agent_metrics m on m.agent_id=a.id where a.owner_id=$1 order by a.created_at desc",[user.id]) as OwnerAgent[]:[];
  return <div className="container py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="eyebrow">Owner console</span><h1 className="mt-4 text-5xl font-black">DASHBOARD</h1><p className="mt-2 text-sm text-neutral-500">Signed in as {user.email}</p></div><div className="flex gap-3"><Link href="/register" className="bg-white px-4 py-2 text-xs font-black text-black">ADD AGENT</Link><SignOutButton/></div></div>
    <div className="mt-10 grid gap-5">{agents.length?agents.map((agent)=><article key={agent.slug} className="border hairline p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h2 className="text-2xl font-black">{agent.name}</h2><span className={`px-2 py-1 text-[10px] font-black ${agent.verified_at?"bg-emerald-400 text-black":"border hairline text-amber-300"}`}>{agent.verified_at?"VERIFIED":"AWAITING WALLET SIGNATURE"}</span></div><p className="mt-2 font-mono text-xs text-neutral-500">{agent.address}</p></div><Link href={`/agent/${agent.slug}`} className="border hairline px-4 py-2 text-xs font-black">PUBLIC PROFILE</Link></div><div className="mt-5 grid grid-cols-2 gap-px bg-white/10 md:grid-cols-4">{[["PORTFOLIO",agent.portfolio_value_usd?`$${Number(agent.portfolio_value_usd).toLocaleString()}`:"—"],["ROI",agent.roi?`${Number(agent.roi).toFixed(2)}%`:"—"],["TRADES",agent.trade_count??"0"],["SYNC BLOCK",agent.last_synced_block??"Not synced"]].map(([label,value])=><div key={label} className="bg-[var(--ink)] p-4"><div className="eyebrow">{label}</div><div className="mt-2 font-mono text-sm">{value}</div></div>)}</div><details className="mt-5"><summary className="cursor-pointer text-xs font-black">EDIT AGENT</summary><EditAgentForm agent={agent}/></details></article>):<div className="border hairline p-10 text-center"><p className="text-neutral-500">No agents registered yet.</p><Link href="/register" className="mt-5 inline-block bg-white px-5 py-3 text-xs font-black text-black">REGISTER YOUR FIRST AGENT</Link></div>}</div>
  </div>;
}
